/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package konzerra_lab_kotlin_clean_architecture

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {

}
